-- Revisit the Bookmarks application that you started working on in a previous lesson. Design a table to store the bookmarks. For each attribute of a bookmark that you can think of, identify the data type, size, whether it can be null, if its a primary key and if a default value makes sense.
-- Create a database named bookmarks owned by dunder_mifflin.
createdb -U dunder_mifflin bookmarks
psql -U dunder_mifflin bookmarks


-- Write an SQL script to automate the creation of the bookmarks table in the database and seeds the table with some data.
-- Create the table anew
CREATE TABLE bookmarks (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title TEXT NOT NULL,
url varchar(50) NOT NULL,
description varchar(50) DEFAULT '',
rating INTEGER CHECK(rating > 0 AND rating <= 5) NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
INSERT INTO bookmarks (title, url, description, rating)
VALUES
('google', 'https://www.google.com', 'Description here', 5),
('google', 'https://www.google.com', '', 1);

--Error Testing
--Giving description an empty value and rating vaue is >5
INSERT INTO bookmarks (title, url, description, rating)
VALUES
   ('google', 'https://www.google.com', , 5),
   ('nap', 'https://www.google.com/','Testing 6', 6);
  
--Not including the description in inserting a value
INSERT INTO bookmarks (title, url, description, rating)
VALUES 
('check this', 'https://www.google.com/', 5);


--SQL Scripts
SELECT * FROM bookmarks;
SELECT * FROM bookmarks where rating > 2;